name: 'Node.js with pnpm'
description: 'Setup Node.js and install dependencies using pnpm'

inputs:
  working-directory:
    description: 'keyword specifies the working directory where the command is run.'
    required: false
    default: '.'

runs:
  using: 'composite'

  steps:
    - name: pnpm setup
      uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0

    - name: Setup Node.js
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version-file: ${{ inputs.working-directory }}/package.json
        # Required for publishing packages to npm
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --ignore-scripts
      working-directory: ${{ inputs.working-directory }}

    - name: Build workspace packages
      shell: bash
      run: pnpm -r run build
      working-directory: ${{ inputs.working-directory }}
