# https://pnpm.io/settings
#
# ```bash
# pnpm config list
# ```

# 使用するNode.jsのバージョン
useNodeVersion: 22.21.1

packages:
  - 'packages/*'
  - 'apps/nozo/*'

# モノレポのpackagesもシンボリックリンクで管理する
linkWorkspacePackages: true

# 依存解決のうまくいっていないdependenciesのdependenciesをrootのnode_modulesまで巻き上げる
publicHoistPattern:
  - '@types/*'
  - '*eslint*'
  - '*prettier*'
  - '*storybook*'

# pinバージョンでインストールする
savePrefix: ''
