# https://pnpm.io/settings
#
# ```bash
# pnpm config list
# ```

# 使用するNode.jsのバージョン
useNodeVersion: 22.21.1

packages:
  - 'packages/*'
  - 'apps/nozo/*'

# モノレポのpackagesもシンボリックリンクで管理する
linkWorkspacePackages: true

# 依存解決のうまくいっていないdependenciesのdependenciesをrootのnode_modulesまで巻き上げる
publicHoistPattern:
  - '@types/*'
  - '*eslint*'
  - '*prettier*'
  - '*storybook*'

# pinバージョンでインストールする
savePrefix: ''

# npmサプライチェーン攻撃対策
# https://pnpm.io/blog/2025/12/05/newsroom-npm-supply-chain-security

# 新しく公開されたパッケージのインストールを3日間遅延させる
minimumReleaseAge: 4320 # 3日間 (3 × 24 × 60分)
minimumReleaseAgeExclude:
  - '@nozomiishii/*'

# 新しいバージョンの認証が古いバージョンよりも弱い場合、インストールは失敗する
# trustPolicy: no-downgrade
