# https://pnpm.io/settings
#
# ```bash
# pnpm config list
# ```

# 使用するNode.jsのバージョン
useNodeVersion: 22.21.1

packages:
  - 'packages/*'
  - 'apps/nozo/*'

# モノレポのpackagesもシンボリックリンクで管理する
linkWorkspacePackages: true

# 依存解決のうまくいっていないdependenciesのdependenciesをrootのnode_modulesまで巻き上げる
publicHoistPattern:
  - '@types/*'
  - '*eslint*'
  - '*prettier*'
  - '*storybook*'

ignoredBuiltDependencies:
  - '@evilmartians/lefthook'

# lifecycle scriptsのlogを全部表示する
reporter: append-only

# pinバージョンでインストールする
savePrefix: ''

# 新しく公開されたパッケージのインストールを3日間遅延させる（セキュリティ対策）
minimumReleaseAge: 4320 # 3日間 (3 × 24 × 60分)
minimumReleaseAgeExclude:
  - '@nozomiishii/*'
