[package]
name = "nozo"
description = "Nozomi config manager"
version = "0.0.0"
edition = "2021"
license = "MIT"
authors = ["Nozomi Ishii"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
