name: Lint GitHub Actions workflows

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  actionlint:
    uses: nozomiishii/workflows/.github/workflows/actionlint.yaml@6fbad8d23b6c361be28cd5d9b67731f8173d63f3 # v2.0.0
