name: Pull Request title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

permissions: {}

jobs:
  pull-request:
    permissions:
      pull-requests: write # write: format revert PR titles, read: validate PR titles
    uses: nozomiishii/workflows/.github/workflows/pull-request.yaml@5b5144ce29ab8cf022d0b69227a76445f2b75a79 # v3.4.1
