name: Pull Request title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

permissions: {}

jobs:
  pull-request:
    permissions:
      pull-requests: write # write: format revert PR titles, read: validate PR titles
    uses: nozomiishii/workflows/.github/workflows/pull-request.yaml@0249f8a5d808a76c9b20604449cb7a15afc6378a # v3.4.0
