name: Pull Request title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read # required by action-semantic-pull-request to read the PR title via the GitHub API

jobs:
  pull-request:
    uses: nozomiishii/workflows/.github/workflows/pull-request.yaml@0bff52c601e5f02549aef27a2f9d6e39c06e563e # v3.2.0
