name: Secret scan

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  secret-scan:
    uses: nozomiishii/workflows/.github/workflows/secret-scan.yaml@587df5685b2ce224cfaf0dd6e42a11954f154d9f # v3.3.1
