name: Secret scan

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  secret-scan:
    uses: nozomiishii/workflows/.github/workflows/secret-scan.yaml@5b5144ce29ab8cf022d0b69227a76445f2b75a79 # v3.4.1
