name: Secret scan

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  secret-scan:
    uses: nozomiishii/workflows/.github/workflows/secret-scan.yaml@bdea1e0028e1f3c1ba9411f8024c1b247d0bfff7 # v3.1.2
