name: Secret scan

on:
  workflow_dispatch:
  # Remove push trigger for team development
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

        # https://github.com/gitleaks/gitleaks-action
        # gitleaksを使って過去のcommitで漏洩してないか確認できる
        #
        # docker run --rm -v "$(pwd):/workspace" -w /workspace zricethezav/gitleaks:latest detect --source=/workspace --verbose --redact --log-opts="--all --full-history"

      - name: Secretlint
        # https://github.com/secretlint/secretlint
        #
        # To run locally, execute the following command:
        # docker run -v `pwd`:`pwd` -w `pwd` --rm -it secretlint/secretlint secretlint "**/*"
        uses: docker://secretlint/secretlint:v11.7.1@sha256:c162d660f31bed078f8a70161a8dde2ca22610d2a8f2e51a375ee8c6cf277b40
        with:
          args: secretlint "**/*"
