name: Commit

on:
  workflow_dispatch:
  push:

defaults:
  run:
    shell: bash

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Lint commit message
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: commitlint.config.cjs
