name: Delete Branch

on:
  pull_request:
    types: [closed]
  push:
    branches: [main]

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Delete Branch
        if: github.event.pull_request.merged == true
        run: |
          git push origin --delete ${{ github.event.pull_request.head.ref }}
