name: Markdown lint

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**/*.md'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  markdown-lint:
    runs-on: ubuntu-slim
    steps:
      - name: Check out
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Check for changes
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: changes
        with:
          filters: |
            md:
              - '**/*.md'

      - name: Setup Node
        if: steps.changes.outputs.md == 'true'
        uses: ./.github/actions/setup-node

      - name: lint
        if: steps.changes.outputs.md == 'true'
        run: npx -y markdownlint-cli2 "**/*.md"
