name: Publish nozo to npm

on:
  workflow_dispatch:
  push:
    paths:
      - 'apps/nozo/typescript/package.json'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: pnpm setup
        uses: pnpm/action-setup@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install

      - name: Publish
        run: pnpm publish --filter nozo
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
