name: Publish prettier-config to npm

on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/prettier-config/package.json'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: pnpm setup
        uses: pnpm/action-setup@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Publish
        run: pnpm publish --filter @nozomiishii/prettier-config
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
