name: Publish eslint-config to npm

on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/eslint-config/package.json'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.14.0'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'

      - name: Install modules
        run: yarn install --frozen-lockfile

      - name: Publish
        run: yarn workspace @nozomiishii/eslint-config publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
