name: Pull Request

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: read

defaults:
  run:
    shell: bash

jobs:
  semantic-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017 # v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Disallow scopes by defining a pattern that expects only type: subject
          headerPattern: '^(\w*): (.*)$'
          headerPatternCorrespondence: type, subject
          # Ensure the subject starts with a lowercase letter and contains allowed characters
          subjectPattern: ^[a-z][a-zA-Z0-9 \\-_/@.:()[\]#!]*$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            starts with a lowercase letter and contains only letters,
            numbers, spaces, or the following symbols: - _ / . : ( ) [ ] # ! @
