name: Publish renovate-config to npm

on:
  push:
    paths:
      - 'packages/renovate-config/package.json'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.17.0'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'

      - name: Install modules
        run: yarn install --frozen-lockfile

      - name: Publish
        run: yarn publish:renovate-config
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
