name: Setting File Format Check

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format-check:
    runs-on: ubuntu-slim

    permissions:
      contents: read  # required by actions/checkout to fetch repository code

    steps:
      - name: Check out
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Format Check
        id: format-check
        run: pnpm format

      - name: Tips
        if: failure()
        run: |
          echo 'Try the following command in the project root'
          echo 'pnpm format:fix'
