name: Setting File Format Check

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format-check:
    runs-on: ubuntu-slim

    permissions:
      contents: read # required by actions/checkout to fetch repository code

    steps:
      - name: Check out
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Format Check
        id: format-check
        run: pnpm format

      - name: Tips
        if: failure()
        run: |
          echo 'Try the following command in the project root'
          echo 'pnpm format:fix'

  required:
    needs: [format-check]
    if: always()
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Fail if any required job failed or was cancelled
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: |
          echo "A required job failed or was cancelled"
          exit 1
